### ISSUE TITLE
Update to 401+

### ISSUE THREAD

**Issue by nickmenow** [yarbsemaj/sveltekit-adapter-lambda#17]
Hey @yarbsemaj 

I recently updated to 401 and made code changes to handle the import { env } from '$env/dynamic/private'; for environment variables.  Wondering if you can update the project to accommodate?   

Thank you for your help.   This is a great project to work with.

Best,

Nick

**Comment by yarbsemaj** [comment]
Hi @nickmenow, thank you for making me aware of this change, i will be adding support for this imminently

**Comment by yarbsemaj** [comment]
Hi @nickmenow Iv published a new release that i believe addresses this issue, this has been tagged with v0.11.0

**Comment by nickmenow** [comment]
Hi @yarbsemaj   Thank you for the update.   Perhaps there is an issue is a little deeper than this lib.    

When on sveltekit @401
I put in a console.log(process.env) above the `app.init({
		env: process.env
	});
` line and it only contains the AMZ single env key value.    

When I revert back to the sveltekit @350 tag that I was on the process.env contains all the ENVs that I have in the Lambda > Configuration > Environment Variables.    So something is happening where process.env is not containing the environment variables even before the app.init call.

This is what the single env looks like on @401 when I console.log(process) in the serverless.js file:  `env: {
    _X_AMZN_TRACE_ID: 'Root=1-62f1427e-23cee3dc20721dc40a8992c3;Parent=75a39d072a6f6b03;Sampled=0'
  }`

**Comment by yarbsemaj** [comment]
Hummmm, that is a weird issue, amazon injects the environment variables when init'ing the function, ill investigate and get back to you

**Comment by nickmenow** [comment]
Thank you for your help.   I'll keep researching also.  Will let you know if I find something.

**Comment by nickmenow** [comment]
I have a work around that uses the .env.[environment] files and using $env/static/private.
