### ISSUE TITLE
How to serve static resources & dynamic content via cloudfront?

### ISSUE THREAD

**Issue by ivands** [yarbsemaj/sveltekit-adapter-lambda#3]
You noted that we can use CloudFront to serve static content from S3 and dynamic content via Lambda.
Could you share how the CloudFormation stack file would look?
I have no idea how to setup CloudFront to do this.

**Comment by yarbsemaj** [comment]
Hi @ivands, i'm currently in process of simplifying the build process so that deployment can be done in one command, im hoping to have this version ready in the next few days.

**Comment by yarbsemaj** [comment]
@ivands This new release is now published as 0.3.1 it should now be possible to deploy with a single command to AWS
