### ISSUE TITLE
node_modules not included in the function code uploads

### ISSUE THREAD

**Issue by JL102** [yarbsemaj/sveltekit-adapter-lambda#30]
Hiya,

When uploading with `serverless deploy` (and/or with `serverless deploy function --function svelte && serverless deploy function --function cfLambda && serverless s3deploy`), it seems that it doesn't include node_modules in the uploaded content. This leads to all of my imported modules failing to load.

Example: (this is my database utilities package)
![image](https://user-images.githubusercontent.com/11487870/215231855-44c99a0a-b7ab-4339-8798-68fa6113d1d3.png)

Is there something I can do during the build step to get node_modules included in the build output? Does esbuild support some sort of tree shaking where it includes only the dependencies that are needed?

**Comment by yarbsemaj** [comment]
Hi @JL102. 
It shouldn't need to be includes as part of the build process within [index.js](https://github.com/yarbsemaj/sveltekit-adapter-lambda/blob/c4605b6d1d5a9475ee56a46dc87e646826e60ef5/index.js#L49) all node modules are bundled by es build into the one file

**Comment by JL102** [comment]
Oh you're right. I need to figure out what's going wrong..... Now it's giving me an error "result not defined" and I dunno why it's changed.

Wish there was a way to see a stack trace.
