### ISSUE TITLE
Dependencies loaded in serverless.js even when SSR is off for those pages

### ISSUE THREAD

**Issue by JL102** [yarbsemaj/sveltekit-adapter-lambda#31]
Hi,

I noticed that in my app, which loads the library `html5-qrcode` in a CSR-only page, `html5-qrcode` is included in the bundle. 

Steps to reproduce: 

1. `npm create svelte@latest my-app`
2. inside `my-app`.... `npm install`
3. `npm install html5-qrcode @yarbsemaj/adapter-lambda`
4. add adapter-lambda to svelte.config.js
5. create `src/routes/qrcode/+page.server.ts`:
```ts
export const ssr = false;
```
6. create `src/routes/qrcode/page.svelte` with a minimum reproducible example of my qrcode page:
```svelte
<div id="reader" bind:this={reader} />

<script lang="ts">
	import { onMount } from 'svelte';
	import { Html5Qrcode, Html5QrcodeSupportedFormats as Formats } from 'html5-qrcode';
	
	let html5QrCode: Html5Qrcode;
	let scanning = false;
	let reader: HTMLDivElement;

	async function startCamera() {
		if (html5QrCode && !scanning ) {
			console.log('Starting camera');
			try {
				await html5QrCode.start(
					{ facingMode: 'environment' },
					{
						fps: 20
					},
					(data => {
						console.log(data);
					}),
					(errorMessage) => {}
				);
				scanning = true;
			} catch (err) {
				scanning = false;
				console.error(err);
			}
		}
	}

	onMount(() => {

		reader.setAttribute('width', '1000px');
		reader.setAttribute('height', '1000px');

		html5QrCode = new Html5Qrcode('reader', {
			formatsToSupport: [Formats.QR_CODE],
			verbose: true
			// useBarCodeDetectorIfSupported: true,
		});

		startCamera();
	});
</script>
```
8. `npm run build` -> the serverless.js bundle includes html5-qrcode, even though the page shouldn't be rendered on the server. 

It seems like html5-qrcode is being included due to this code chunk:
```js
var init_page_svelte2 = __esm({
  "build/entries/pages/qrcode/_page.svelte.js"() {
    "use strict";
    init_shims();
    init_chunks();
    import_html5_qrcode = __toESM(require_cjs(), 1);
    Page2 = create_ssr_component(($$result, $$props, $$bindings, slots) => {
      let reader;
      return `<div id="reader"${add_attribute("this", reader, 0)}></div>`;
    });
  }
});
```
in which `require_cjs` is the entry point for html5-qrcode. Any idea why `qrcode/_page.svelte.js` is being loaded despite ssr being off for that page? It'd be nice to keep the bundle size down by not including libraries that are only loaded on CSR-only pages.

**Comment by yarbsemaj** [comment]
I'm not sure, that does seem odd, Im wondering if this a svelte/vite bug rather than issue with my adapter. When i bundel, it's just to combine the server code with the server.js that svelte produces

**Comment by yarbsemaj** [comment]
Are you able to replicate this issue with the node adapter

**Comment by JL102** [comment]
Hard to tell for certain.

I switched to @sveltejs/adapter-node and did some ctrl+F across `build/client` and `build/server`.
This first screenshot includes a search through build/client, and I believe this file that's open in the editor includes all the `html5-qrcode` source code bundled into a single file.
![image](https://user-images.githubusercontent.com/11487870/225427463-287f2d91-5c10-4269-a02b-ab6ee11e3711.png)

This second screenshot includes a search through build/server, and I believe this may be the same code as I noted in the original post (including the line `import_html5_qrcode = __toESM(require_cjs(), 1);`).
![image](https://user-images.githubusercontent.com/11487870/225428172-7e6105d9-47e0-4059-a580-11787d584eb8.png)

**Comment by yarbsemaj** [comment]
That would be it, the only difference is, when my adapter bundles the code it minifies it
