### ISSUE TITLE
Serverless/SvelteKit/Lambda@Edge CSRF

### ISSUE THREAD

**Issue by michaelcuneo** [yarbsemaj/sveltekit-adapter-lambda#32]
I have a fully working local SvelteKit app that uses form actions, which POST to the server side, and respond accordingly.

This works locally 100% fine, but after deployment using this adapter and `serverless-plugin-cloudfront-lambda-edge` using any form actions responds with the '403 -Forbidden, 'Cross-site POST form submissions are forbidden'.

It appears as though you can modify SvelteKit to ignore CSRF by adding a configuration options to originCheck: false, which works, but then gives me `404 /login not found, strict-origin-when-cross-origin.`.

I ned to find a way to add the ORIGIN to the adapter-lambda or configuration somehow I think?

**Comment by yarbsemaj** [comment]
Hi @michaelcuneo , Thankyou for your interest in my project. 

I will investigate this and get back to you. Do you have a repo I can test with?

**Comment by michaelcuneo** [comment]
For now I've added `csrf: { checkOrigin: false }` to my `svelte.config.ts` and also added a response section to my `hooks.server.ts` handler function to get rid of the CORS issue that occurs when CSRF is off.

```
	const response = await resolve(event);
	
	// Apply CORS header for API routes
	if (event.url.pathname.startsWith('/signup')) {
		// Required for CORS to work
		if(event.request.method === 'OPTIONS') {
			return new Response(null, {
				headers: {
					'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
					'Access-Control-Allow-Origin': '*',
					'Access-Control-Allow-Headers': '*',
				}
			});
		}

		response.headers.append('Access-Control-Allow-Origin', `*`);
	}

	return response;
```

I don't think this will be ideal for security, but it does function.

I'm trying to see a lower level than this in the performRewrite area of the svelte-adaptor but I'm not sure if that'll suit?

**Comment by michaelcuneo** [comment]
I'm guessing that for this to work, it would require a modification to router.js... a secondary performReWrite, with x-forwarded-host headers added to any POST request?

Do you happen to know where Serverless performs it's node build so that I can add ORIGIN to this step? I can't find it anywhere... From what I can see in the SvelteKit documentation though, it only needs one of the solutions, ORIGIN="" in the build step, or X-forwarded-host in t he headers? Unless I'm reading the docs wrong...

**Comment by michaelcuneo** [comment]
I'll make up a quick REPO now aside in my sveltekit-aws-boilerplate for testing and push it up shortly.

**Comment by yarbsemaj** [comment]
Yer, I’m supprised setting the origin ENV did not work as expected.

you also should not need the x forward headers on your options call, those should be sent by your proxy/cdn to get SvelteKit know what your original origin was, it will probably be this weekend before I get round to adding those to the edge, tuning into a busy week and I haven’t had the mental energy to work on this yet :)

**Comment by michaelcuneo** [comment]
I've never set the ORIGIN in ENV because ORIGIN is only picked up by adapter-node as a variable to include in the build.
ORIGIN, PROTOCOL_HEADER and HOST_HEADER are all specific to adapter-node

```
/* global ENV_PREFIX */
const origin = env('ORIGIN', undefined);
const address_header = env('ADDRESS_HEADER', '').toLowerCase();
const protocol_header = env('PROTOCOL_HEADER', '').toLowerCase();
const host_header = env('HOST_HEADER', 'host').toLowerCase();
```

I'll find a way to pull ENV into adapter-lambda, I've tried performing it all in the middle on CloudFront by creating a policy that appends to the forward all http to https by adding a new behaviour with the header policies, but that just gives me access denied straight away, because x-forwarded-proto is denied by Lambda@Edge

**Comment by yarbsemaj** [comment]
Hummmm, for the proto, we might just be able to hard code it to https, as that’s what 99% of users will be using

**Comment by michaelcuneo** [comment]
Yeah of course, no one uses http anymore.

**Comment by yarbsemaj** [comment]
As for the x forward host, you can set its value as the value of the host header (essentially overriding it) when a do the massaging of the lambda event into a request object

**Comment by zamoshchin** [comment]
Having the same issue. Was a solution merged in?

**Comment by yarbsemaj** [comment]
@zamoshchin Not yet, im working on one now, give me a few hours

**Comment by yarbsemaj** [comment]
@zamoshchin  @michaelcuneo I have pushed a fix for this issue as v1.1.0, if you update, make the [requisite changes to your serverless.yml](https://github.com/yarbsemaj/sveltekit-adapter-lambda/commit/7756af16ef61f186912e1f663d82dbd2c6ca663d#diff-8cf16232f3b7094ea431234555d38ad71e6e62764c3e29a5841e25172aea5049) this should fix your issue.

**Comment by yarbsemaj** [comment]
@zamoshchin  @michaelcuneo I have pushed a fix for this issue as v1.1.0, if you update, make the [requisite changes to your serverless.yml](https://github.com/yarbsemaj/sveltekit-adapter-lambda/commit/7756af16ef61f186912e1f663d82dbd2c6ca663d#diff-8cf16232f3b7094ea431234555d38ad71e6e62764c3e29a5841e25172aea5049) this should fix your issue.

**Comment by zamoshchin** [comment]
Thanks for the quick turnaround--I believe that fixed that issue but am not 100% sure as I'm facing a further issue, which I believe is related to needing to set my environment vars. According to the Sveltekit docs I need to run using the command `node -r dotenv/config build` but I'm not sure where that command is being run. All I do is `sls deploy`

**Comment by yarbsemaj** [comment]
@zamoshchin If those ENVs are in relation to the ones discussed above, there not needed, that was just me misreading some docs. If you want to set ENVs on your svelte lambda, this should be done in your [serverless.yml](https://medium.com/@HussainAliAkbar/serverless-managing-environment-variables-efficiently-with-stages-part-1-90c4465d2e64#2e52)

**Comment by gudata** [comment]
@yarbsemaj why not build by seting the HOST_HEADER to "host"? Cloudfront pass the HOST with AllViewerAndCloudFrontHeaders-2022-06 and AllViewer policies.

```PROTOCOL_HEADER=x-forwarded-proto HOST_HEADER=host npm run build ; ?```

I just did it and it worked for me
