### ISSUE TITLE
Dependency incompatibility with Sentry - No loader is configured for ".node" files

### ISSUE THREAD

**Issue by plourenco** [yarbsemaj/sveltekit-adapter-lambda#40]
Hi,

It seems there's a dependency incompatibility when using the adapter with sentry (`@sentry/sveltekit`). If you install sentry packages while using the adapter, the following error will occur when building:

```
> Using adapter-serverless
✘ [ERROR] No loader is configured for ".node" files: node_modules/fsevents/fsevents.node

    node_modules/fsevents/fsevents.js:13:23:
      13 │ const Native = require("./fsevents.node");
```

To reproduce the problem the package `@sentry/sveltekit` needs to be installed and imported in `hooks.server.ts`.

```javascript
import * as Sentry from '@sentry/sveltekit';

export const handle = Sentry.sentryHandle();
```

**Comment by yarbsemaj** [comment]
Hi @plourenco thank you for your interest in my project.

This looks to be a problem when using vite with esbuild, would you mind trying this solution and reporting back?

https://stackoverflow.com/a/75655669

Thanks James

**Comment by plourenco** [comment]
Hi James,
Unfortunately, that didn't seem to do the trick, I suspect that might not be the cause. I'll set up a sandbox with a reproducible example in case it helps narrow down the problematic dependency. Thanks!

**Comment by yarbsemaj** [comment]
Hi @plourenco
Thanks for trying that, a sandbox project would really help. The server bundle is quite simple with minimal external dependencies. The only thing really added is svelte’s own node polyfills (and a library that handles some of the cookie stuff)

**Comment by plourenco** [comment]
Hi @yarbsemaj 
Yes, that makes sense, it's quite odd. Here's an empty sveltekit project with `@yarbsemaj/adapter-lambda` and `@sentry/sveltekit`. The issue should arrise at the end of the build step (`npm run build`), however, building succeeds if both lines of `hooks.server.ts` (sentry import and handle) are commented out.

**Comment by yarbsemaj** [comment]
Thanks @plourenco i’m not sure I’ll have time to look at this in the next week unfortunately as I’m away from my desk, but I will when I get back :)

**Comment by yarbsemaj** [comment]
Hi @plourenco 
I was unable to recreate the issue you were seeing, in fact it built and deployed fine and is running on https://d3airuk00m0jmc.cloudfront.net/ if you wish to check it out. I had to install `@babel/preset-typescript` as it complained without it for some reason.

I know "it works on my machine" is a bit of an unsatisfactory outcome so i've [raised a PR](https://github.com/plourenco/svelte-sentry-lambda/pull/1) with a docker file in it that when built and run with the commands in the readme will build and deploy your application.

It may look like nothing is happening for a while, but i think that's an issue with serverless running inside docker, I think adding --verbose to the end of the `CDM` line in the `Dockerfile` and rebuilding the image it should give you more feedback.

Thanks
James

**Comment by plourenco** [comment]
Hello @yarbsemaj,

Thank you for your efforts in troubleshooting this, that's for sure more than satisfactory 👍
It seems that even while running with docker, I got the same fsevents loader error log. I've tried running with `node18`, building for amd64 (I'm using arm64) but no luck yet.

Nevertheless, given that you were not able to reproduce it and deployment is running just fine, I'm closing this issue for now until I can better narrow down the cause. If I have more information, I'll add a few comments or re-open it.

Thanks once again.

**Comment by plourenco** [comment]
Hi @yarbsemaj, thanks again for all your help earlier.

I’ve done a deeper investigation into the issue and finally narrowed it down. The problem is specifically caused by importing `@sentry/sveltekit` in **server-side/SSR builds** - not by your adapter directly. It worked fine doing dynamic imports and doing sentry exception capturing within the browser.

Here’s what I believe is happening:
- `@sentry/sveltekit` depends on `@sentry/vite-plugin`, which brings in (possibly chokidar?), which optionally requires fsevents.
- During the server build, your adapter invokes esbuild.buildSync(), which eagerly walks all dependencies.
- This traversal hits fsevents, which includes a native .node file. Since no loader is defined for .node, esbuild throws a fatal error.

Vite normally avoids this issue because it externalizes such modules, or tree-shakes them away depending on usage. But with raw esbuild, it needs to be explicitly told to skip fsevents.

The fix was simple: I've passed this override into your adapter’s esbuild.buildSync() call:
```
esbuildOverride: {
  external: ['fsevents']
}
```
Once I apply that, the build completes normally - even with @sentry/sveltekit imported. Let me know if you'd like to change something in regard to this.
