### ISSUE TITLE
no such file or directory, scandir 'build/prerendered'

### ISSUE THREAD

**Issue by scurrilus-funke** [yarbsemaj/sveltekit-adapter-lambda#5]
Hi, thank you for this solution.

i was running into a problem were build process displays an error.

`ENOENT: no such file or directory, scandir 'build/prerendered'`

it came from @yarbsemaj/adapter-lambda/index.js
`const prerendered_directory = join(out, 'prerendered');`

The solution was to add `export const prerender = true;` to one of my pages. For example index.svelte
https://kit.svelte.dev/docs/page-options#prerender. The prerender folder is missing if i don`t do that. This is why the build fails.

Is it possible to make this voluntarily in a future Version of this adapter?

Many Thanks and happy coding
Cheers Peter

**Comment by yarbsemaj** [comment]
Hi @scurrilus-funke, thank you for your interest in my project.

Thankyou, for spotting this bug, iv just published a new version, 0.4.2, that I believe should fix the issue you described.

**Comment by scurrilus-funke** [comment]
Perfect it works! Thank you.
