### ISSUE TITLE
app.js no longer exists?

### ISSUE THREAD

**Issue by kansai-gaijin** [yarbsemaj/sveltekit-adapter-lambda#6]
SvelteKit : 1.0.0-next.281

app.js is no longer output by build.
I believe it is now index.js

App class has also been renamed to Server.

App class render function has been renamed to respond.

**Comment by yarbsemaj** [comment]
Hi @kansai-gaijin, iv published an updated package 0.5.0 that should work with the very latest sveltkit version

**Comment by kansai-gaijin** [comment]
worked like a charm friend! I love the work you are doing!
