### ISSUE TITLE
Building fails.

### ISSUE THREAD

**Issue by ivands** [yarbsemaj/sveltekit-adapter-lambda#8]
When building I get the following error.

```> Build failed with 1 error:
build/server/_serverless.js:2:21: error: Could not resolve "../index.js"
```

**Comment by DanielRios549** [comment]
The same here

**Comment by yarbsemaj** [comment]
Hi @ivands @DanielRios549, Thanks for taking an interest in my project. 

I think the issue may be the version of my adapter, and the version of svelte kit you are using are incompatible, could you try instead using v0.4.2 and let me know if that fixes your issue. 

To give you an idea of how fast the adapter API is changing, a last released a build 19 days ago, to fix issues with the then current API, those changes are already out of date and the Svelte team seem to have changed the way that want to do things yet again.

**Comment by yarbsemaj** [comment]
You may also want to rebase your project onto the latest svelte kit build 1.0.0-next.301 and use the latest adapter version

**Comment by ivands** [comment]
Upgrading to 1.0.0-next.301 doesn't help.
The build folder doesn't have an index.js file inside.

**Comment by ivands** [comment]
Upgrading the adapter to 0.6.0 fixed the issue tho.

**Comment by yarbsemaj** [comment]
Hi @ivands That is expected behaviour as the file is removed at the [end of the build process](https://github.com/yarbsemaj/sveltekit-adapter-lambda/blob/5714fda08302da9bbd893d675fb383cacde4ec97/index.js#L81). 

Im glad updating fixed your issue however :)
