### ISSUE TITLE
Unnecessary ApiGateway

### ISSUE THREAD

**Issue by ivands** [yarbsemaj/sveltekit-adapter-lambda#9]
I feel like your serverless.yaml file unnecessary uses ApiGateway, leading to unnecessary costs on scale.
Would it be possible to let CloudFront call the lambda directly?

I found this forum post about it.
https://forum.serverless.com/t/directly-proxying-lambda-via-cloudfront-without-api-gateway/3808/4

Or even better would be to host the whole svelte SSR lambda on the edge.
But that would probably not work because of constraints on the edge.

**Comment by ivands** [comment]
AWS did at some point leak info about a new feature that would allow you to get a public-facing URL for your lambda.
https://beabetterdev.com/2021/11/21/aws-releases-lambda-function-urls-finally/
But sadly they still haven't released this feature.

**Comment by yarbsemaj** [comment]
Hi @ivands, Interesting concept discussed in the thread you referenced. I wasn't aware this was possible outside of edge Lambdas, you learn something new every day 😄. Doing a bit more digging through that thread,unfortunately I hit a blocker with this approach...

> Lambda can only return JSON. API Gateway can use transforms to change that JSON into other things. For example if a lambda returns HTML as a JSON result, API Gateway can strip the JSON and return an HTML page.

Iv tested this out and It does appear to be the case. I'm also unsure how you would do thing like set headers and cookies without API Gateway (and lambda proxy)

As Lambda@edge functions can't read the contents of a response body it's not possible to emulate this function at the edge.

**Comment by ivands** [comment]
That does seem to be a blocker.
I guess some kind of transformation step is still needed.
Sadly ApiGateway is kinda expensive for this use case.

**Comment by ivands** [comment]
Hi @yarbsemaj, that's a great improvement. To eliminate API Gateway entirely we will just have to wait for native lambda support in CloudFront.
